### ISSUE TITLE
只能收集infohash？不能添加例如名称、时间等？

### ISSUE THREAD

**Issue by xinshangshangxin** [beilunyang/dhtCrawler#1]
只是收集infohash，有什么意义呢？

**Comment by beilunyang** [comment]
获取到infohash

**Comment by xinshangshangxin** [comment]
只有 infohash 的作用是什么？  只有hash，没有任何名称等信息啊

**Comment by beilunyang** [comment]
获取到infohash后，你就可以通过第三方网站下载种子文件(简单方式)，或者自己实现一个bt客户端下载种子文件(需要实现bt协议，有难度)，获取到详细信息。

**Comment by xinshangshangxin** [comment]
就是重新通过 infohash 获取文件名称等?
如果是这样，就没有太大必要了，不能实现简单的基于文件名称的搜索，采集了hash也没有办法直接使用。。。

**Comment by beilunyang** [comment]
dht爬虫就只是加入dht网络，然后被动地获取infohash。如果你想实现一个搜索引擎，就还需要实现一个解析模块，获取到metadata。方法就是我上面和你说的那两个方法或者实现bep_0009协议（http://www.bittorrent.org/beps/bep_0009.html ）。 
给你个dht爬虫 + metadata解析的具体实现。https://github.com/78/ssbc  
如果你对dht感兴趣，可以再翻翻这份文档：http://www.bittorrent.org/beps/bep_0005.html

**Comment by xinshangshangxin** [comment]
thanks
