### ISSUE TITLE
如何将爬虫放到vps上运行?

### ISSUE THREAD

**Issue by zenghuazhe** [beilunyang/dhtCrawler#4]
你好，无意间看到你在v2ex那个dht爬虫的帖子，很感兴趣，所以自己也尝试用java写了一个。想向您请教一下，我已经在vultr买了个vps，然后下载了Xshell...之后不知道该怎么操作了。把java工程编译后如何“塞”进那个机子并运行呢?

**Comment by DogtorDoggo** [comment]
打包成jar

**Comment by zenghuazhe** [comment]
非常感谢！
